version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: wakatime-blockchain-tracker
    ports:
      - "${ROCKET_PORT:-8000}:${ROCKET_PORT:-8000}"
    environment:
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      - ROCKET_PORT=${ROCKET_PORT}
      - ROCKET_ENV=${ROCKET_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_KEY=${API_KEY}
    env_file:
      - .env
