name: Scheduled Docker Run

jobs:
  spin_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            -t solana-tracker:latest \
            .

      - name: Run Docker container
        run: |
          docker run --rm  \
          -e RUST_LOG="debug" \
          -e WAKA_KEY=${{ secrets.WAKA_KEY }} \
          -e KEYPAIR=${{ secrets.KEYPAIR }} \
          -e BURN_ID=${{ secrets.BURN_ID }} \
          -e VAULT_ID=${{ secrets.VAULT_ID }} \
          -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
          -e RPC_URL=${{ secrets.RPC_URL }} \
          -e CLUSTER=${{ secrets.CLUSTER }} \
          -e FEE_LAMPORTS_AMOUNT=${{ secrets.FEE_LAMPORTS_AMOUNT }} \
          solana-tracker:latest